inherit_from: .rubocop_todo.yml

Metrics/MethodLength:
  Max: 20

Lint/NonLocalExitFromIterator:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
