version: '3'
services:
  db:
    image: postgres
    container_name: db_host
  web:
    build: .
    environment:
      HOST_NAME: db_host
    entrypoint: /myapp/entrypoint.sh
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
